---
- name: Run Simple Command
  hosts: all
  become: yes
  become_method: sudo
  tasks:
  - name: Run command on ubuntu server
    shell:
          "echo 'This is added via playbook' > /tmp/playbook_check"
